ToDoCore.Web/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoCore.Web.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

ToDoCore.Web/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoCore.Business.Dto;
using ToDoCore.Business.Interfaces;

namespace ToDoCore.Web.Controllers
{
    public class ToDoController : Controller
    {
        IToDoRepository toDoRepository;
        ITaskRepository taskRepository;
        IReminderRepository reminderRepository;
        public ToDoController(IToDoRepository _toDorepository, ITaskRepository _taskRepository, IReminderRepository _reminderRepository)
        {
            toDoRepository = _toDorepository;
            taskRepository = _taskRepository;
            reminderRepository = _reminderRepository;
        }

        public IActionResult Index()
        {
            return View(toDoRepository.ListForMain(string.Empty));
        }

        public PartialViewResult Search(string keyword)
        {
            return PartialView("_ToDoList", toDoRepository.ListForMain(keyword));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new ToDoDto());
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var model = toDoRepository.Read(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = toDoRepository.Read(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ToDoDto toDoItem)
        {
            toDoRepository.Update(toDoItem);
            return View(toDoItem);
        }

        [HttpPost]
        public JsonResult Create(ToDoDto toDoItem)
        {
            toDoItem = toDoRepository.Create(toDoItem);
            return Json(toDoItem);
        }

        [HttpGet]
        public IActionResult TaskModal(int id, int todoid)
        {
            TaskDto taskDto;
            if (id > 0)
                taskDto = taskRepository.Read(id);
            else
                taskDto = new TaskDto { ToDoId = todoid };

            return PartialView("_TaskModal", taskDto);
        }

        [HttpPost]
        public JsonResult SaveTask(TaskDto taskItem)
        {
            if (taskItem.Id > 0)
                taskRepository.Update(taskItem);
            else
                taskItem = taskRepository.Create(taskItem);

            return Json(taskItem);
        }

        [HttpGet]
        public IActionResult ReminderModal(int id, int taskid)
        {
            ReminderDto reminderDto;
            if (id > 0)
                reminderDto = reminderRepository.Read(id);
            else
                reminderDto = new ReminderDto { TaskId = taskid, RemindTo = DateTime.Now };

            return PartialView("_ReminderModal", reminderDto);
        }

        [HttpPost]
        public JsonResult SaveReminder(ReminderDto reminderItem)
        {
            if (reminderItem.Id > 0)
                reminderRepository.Update(reminderItem);
            else
                reminderItem = reminderRepository.Create(reminderItem);

            return Json(reminderItem);
        }
    }
}

ToDoCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoCore.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ToDo" asp-action="Index" class="navbar-brand">ToDoCore.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="ToDo" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="ToDo" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ToDoCore.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoCore.Web/Views/Shared/_ToDoList.cshtml
@model IList<ToDoCore.Business.Dto.ToDoMainDto>
@if (Model != null)
{
    foreach (ToDoCore.Business.Dto.ToDoMainDto todoItem in Model)
    {
        <div class="col-md-4" style="height:250px !important; display:grid;">
            <div class="thumbnail">
                <div class="caption">
                    <h3> @todoItem.Subject </h3>
                </div>
                <p>@todoItem.Description</p>

                <div class="" style="padding-bottom:0px;">
                    <div class="alert-danger">
                        <span class="">@todoItem.CountTask</span>
                        <span class="glyphicon glyphicon-flag">Task </span>
                    </div>
                    <div class="alert-danger">
                        <span class="">@todoItem.CountReminder</span>
                        <span class="glyphicon glyphicon-time">Reminder </span>
                    </div>
                    <br />
                    <a id="btnDetail" class="btn btn-sm btn-primary" href="@Url.Action("Detail","ToDo",new { id = todoItem.Id })" role="button">Detail &raquo;</a>
                    <a id="btnEdit" class="btn btn-sm btn-warning" href="@Url.Action("Edit","ToDo",new { id = todoItem.Id })" role="button">Edit &raquo;</a>
                </div>
            </div>
        </div>
    }
}

ToDoCore.Web/Views/ToDo/Create.cshtml
@model ToDoCore.Business.Dto.ToDoDto
@{
    ViewData["Title"] = "Detail";
}


<h2><span class="text-info">Create New ToDo Item</span></h2>
<div class="container">
    <form id="frmToDo">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="CreateDate" value="@Model.CreateDate" />
        <div class="form-group">
            <label for="Subject">Subject</label>
            <input type="text" class="form-control" name="Subject" placeholder="Subject" value="@Model.Subject" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea class="form-control" name="Description" placeholder="Description" rows="5" id="comment">@Model.Description</textarea>
        </div>
    </form>

    <label for="Description">Task Items</label>
    <p>
        <span class="bg-warning">
            (You can create Task and Reminders after create ToDo Item)
        </span>
    </p>
    <div class="row col-md-1 col-lg-offset-11">
        <a class="btn btn-lg btn-success createToDo" style="margin-top:20px;" href="#">
            <span class="glyphicon glyphicon-floppy-disk"></span>
        </a>
    </div>
</div>

ToDoCore.Web/Views/ToDo/Detail.cshtml
@model ToDoCore.Business.Dto.ToDoDto
@{
    ViewData["Title"] = "Detail";
}

<div class="container">
    <div class="row">
        <div class="col-md-11">
            <h1>@Model.Subject</h1>
        </div>
        <div class="col-md-1">
            <a class="btn btn-lg btn-warning" style="margin-top:20px;" href="@Url.Action("Edit", "ToDo", new { id = Model.Id })">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
        </div>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <p>@Model.Description</p>
    </div>
    <label for="Description">Task Items</label>
    @if (Model.TaskDtos != null)
    {
        foreach (var taskItem in Model.TaskDtos)
        {
            <div class="form-group bg-success">
                <div class="row">
                    <div class="col-md-12">
                        <div class="thumbnail">
                            <div class="caption">
                                <h3>@taskItem.Subject</h3>
                            </div>
                            <p>@taskItem.Description</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Description" style="padding-left:20px;">Remind Items</label>
                        <div class="row" style="padding-left:20px; padding-right:20px;">
                            @if (taskItem.ReminderDtos != null)
                            {
                                if (taskItem.ReminderDtos.Count > 0)
                                {
                                    foreach (var remindItem in taskItem.ReminderDtos)
                                    {
                                        <div class="col-md-3">
                                            <div class="thumbnail">
                                                <div class="caption">
                                                    <p> @remindItem.RemindTo.ToShortDateString() </p>
                                                    <p>@remindItem.Message</p>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    <div class="col-md-3" style="padding-left:20px;">
                                        <p>(No Reminder)</p>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>

            </div>
        }
    }
</div>

ToDoCore.Web/Views/ToDo/Edit.cshtml
@model ToDoCore.Business.Dto.ToDoDto
@{
    ViewData["Title"] = "Detail";
}

<h2><span class="text-info">Edit ToDo Item</span></h2>
<div class="container">
    <form id="frmToDo">
        <input id="todoId" type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="CreateDate" value="@Model.CreateDate" />
        <div class="form-group">
            <label for="Subject">Subject</label>
            <input type="text" class="form-control" name="Subject" placeholder="Subject" value="@Model.Subject" />
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea class="form-control" name="Description" placeholder="Description" rows="5" id="comment">@Model.Description</textarea>
        </div>
    </form>

    <label for="Description">Task Items</label>
    <a href="#" data-todoid="@Model.Id" class="btn btn-xs btn-success taskModalPopup"><span class="glyphicon glyphicon-plus"></span></a>

    @if (Model.TaskDtos != null)
    {
        foreach (var taskItem in Model.TaskDtos)
        {
            <div class="form-group bg-success">
                <div class="row">
                    <div class="col-md-12">
                        <div class="thumbnail">
                            <div class="caption">
                                <div class="row">
                                    <div class="col-md-11">
                                        <h3>@taskItem.Subject</h3>
                                    </div>
                                    <div class="col-md-1">
                                        <a href="#" data-todoid="@Model.Id" data-taskid="@taskItem.Id" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                                        <a href="#" data-todoid="@Model.Id" data-taskid="@taskItem.Id" class="btn btn-xs btn-warning taskModalPopup"><span class="glyphicon glyphicon-pencil"></span></a>
                                    </div>
                                </div>
                            </div>
                            <p>@taskItem.Description</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label style="padding-left:20px;" for="Description">Remind Items</label>
                        <a href="#" data-taskid="@taskItem.Id" class="btn btn-xs btn-success reminderModalPopup"><span class="glyphicon glyphicon-plus"></span></a>
                        <div class="row" style="padding-left:20px; padding-right:20px;">
                            @if (taskItem.ReminderDtos != null)
                            {
                                if (taskItem.ReminderDtos.Count > 0)
                                {
                                    foreach (var remindItem in taskItem.ReminderDtos)
                                    {
                                        <div class="col-md-3">

                                            <div class="thumbnail">
                                                <div class="caption">
                                                    <p> @remindItem.RemindTo.ToShortDateString() </p>
                                                    <p>@remindItem.Message</p>
                                                </div>

                                                <a href="#" data-reminderid="@remindItem.Id" data-taskid="@taskItem.Id" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
                                                <a href="#" data-reminderid="@remindItem.Id" data-taskid="@taskItem.Id" class="btn btn-xs btn-warning reminderModalPopup"><span class="glyphicon glyphicon-pencil"></span></a>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    <div class="col-md-3" style="padding-left:20px;">
                                        <p>(No Reminder)</p>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>

            </div>
        }
    }

    <div class="row col-md-1 col-lg-offset-11">
        <a class="btn btn-lg btn-success updateToDo" style="margin-top:20px;" href="#">
            <span class="glyphicon glyphicon-floppy-disk"></span>
        </a>
    </div>
</div>

<div id="myModal" class="modal">
    <div class="modal-dialog" style="width:350px; height:200px;">
        <div class="modal-content" style="overflow: auto; padding:15px;">
            <div style="height:10px;"> </div>
            <div id="myModalContent" style="width:300px; height:150px; ">
            </div>
        </div>
    </div>
</div> 

ToDoCore.Web/Views/ToDo/Index.cshtml
@model IList<ToDoCore.Business.Dto.ToDoMainDto>
@{
    ViewData["Title"] = "Index";
}


<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">ToDo List Project</h1>
        <p class="lead text-muted">Created by Altay Gençaslan for Netsparker Company</p>
        <p>
            <div class="row">
                <div class="col-md-3 col-md-offset-3 right">
                    <input type="text" id="txtSearch" class="form-control" placeholder="Search in ToDo">
                </div>
                <div class="col-md-2">
                    <a href="@Url.Action("Create","ToDo")" class="btn btn-primary my-2">Create New</a>
                </div>
            </div>
        </p>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div id="divToDoList" class="row">
            @Html.Partial("_ToDoList", Model)
        </div>
    </div>
</div>

ToDoCore.Web/Views/ToDo/_ReminderModal.cshtml
@model ToDoCore.Business.Dto.ReminderDto
<form id="frmReminder">
    <input type="hidden" name="Id" value="@Model.Id" />
    <input type="hidden" name="TaskId" value="@Model.TaskId" />
    <div class="col-md-12">
        <h3 class="modal-title">Reminder</h3>
        <div class="caption">
            <input class="form-control" type="text" name="Message" placeholder="Message" value="@Model.Message" />
        </div>
        <p>
            <input id="RemindTo" type="datetime" class="form-control" name="RemindTo" value="@Model.RemindTo.ToString("dd/MM/yyyy hh:mm")" />
        </p>

        <a class="btn btn-success btnSaveReminder" href="#">Save</a>
    </div>
</form>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/lib/jquery/dist/jquery.mask.min.js"></script>
<script>
    $('#RemindTo').mask("99/99/9999 99:99", { placeholder: 'DD/MM/YYYY HH:MM' });

    $(".btnSaveReminder").on("click", function (e) {
        var serializeItem = $('#frmReminder').serialize();
        $.ajax({
            url: '/ToDo/SaveReminder',
            type: 'POST',
            content: 'application/json;',
            dataType: 'json',
            data: serializeItem,
            success: function (data) {
                window.location.reload();
            }
        });
    });
</script>

ToDoCore.Web/Views/ToDo/_TaskModal.cshtml
@model ToDoCore.Business.Dto.TaskDto
<form id="frmTask">
    <input type="hidden" name="Id" value="@Model.Id" />
    <input type="hidden" name="ToDoId" value="@Model.ToDoId" />
    <div class="col-md-12">
        <h3 class="modal-title">Task</h3>
        <div class="caption">
            <input class="form-control" type="text" name="Subject" placeholder="Subject" value="@Model.Subject" />
        </div>
        <p>
            <textarea class="form-control" name="Description" placeholder="Description" rows="5" id="comment">@Model.Description</textarea>
        </p>

        <a class="btn btn-success btnSaveTask" href="#">Save</a>
    </div>
</form>

<script>
    $(".btnSaveTask").on("click", function (e) {
        var serializeItem = $('#frmTask').serialize();
        $.ajax({
            url: '/ToDo/SaveTask',
            type: 'POST',
            content: 'application/json;',
            dataType: 'json',
            data: serializeItem,
            success: function (data) {
                window.location.reload();
            }
        });
    });
</script>